name: Generate Lighthouse Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse CI
        run: |
          echo "Collecting Lighthouse data..."
          lhci collect --url https://google.com --numberOfRuns=3 --output=json --output-path=.lighthouseci/report.json
          echo "Uploading Lighthouse data..."
          lhci upload --target=temporary-public-storage

      - name: List Lighthouse Report Files
        run: ls -alh .lighthouseci/

      - name: Upload Lighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: .lighthouseci/report.json
